spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema
    username: postgres
    password: 1234
    driver: org.postgresql.Driver

server:
  port: 8080

application:
    admin-auth-header:
      header-value: secretadmin123